name: Get next package versions
description: Get next versions for changed packages.

inputs:
  GH_TOKEN:
    description: Github token.
    required: true

outputs:
  next-packages-list:
    description: A list of packages with their new versions.
    value: ${{ steps.get-next-package-versions.outputs.next-packages-versions }}

runs:
  using: "composite"
  steps:
    - id: get-next-package-versions
      shell: bash
      run: |
        next_packages_versions_json=$(npx lerna version --conventional-commits --yes --no-git-tag-version --no-push --no-changelog --json --loglevel=error)
        next_packages_list=$(echo "$next_packages_versions_json" | jq -r '.[] | "\(.name)@\(.version)"')

        echo "packages list json $next_packages_versions_json"
        echo "packages list $next_packages_list"

        echo "next-packages-list<<EOF" >> $GITHUB_OUTPUT
        echo "$next_packages_list" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
