name: Set Git credentials
description: Defines Git credentials for the author.

runs:
  using: "composite"
  steps:
    - name: Set Git identity
      shell: bash
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
